spring:
  profiles:
    active: dev

---

spring:
  profiles: dev

server:
    port: 8585

properties:
  user:
    name: admin
    password: admin

---

spring:
  profiles: docker

server:
    port: 8585

properties:
  user:
    name: admin
    password: admin

